apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert
spec:
  secretName: wordpress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - projectonellereafitxd.software
