apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  #No namespace, PVs are global
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Mi
  storageClassName: nfs
  nfs:
    path: "/"
    server: fs-0deb1bccd86078aa4.efs.us-east-1.amazonaws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi